# Generated by Django 3.2.20 on 2025-03-09 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20250227_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancellation_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
